// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-app-overview.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
var OVERVIEW = {
  name: "SimSelf",
  summary: "A browser-based simulated-self app: a webcam drives real-time body/hand pose tracking (MediaPipe), facial emotion analytics (face-api.js in a Web Worker), and a 3D humanoid robot avatar rendered with Three.js, plus a streaming voice chat pipeline.",
  capabilities: [
    "MediaPipe pose + hand landmark tracking with mirror/direct view modes",
    "SVD-based hand calibration mapping palm pose to 3D rotation with One-Euro smoothing",
    "Facial emotion detection offloaded to a Web Worker with tunable detector thresholds",
    "3D humanoid robot avatar driven by live landmarks",
    "Streaming voice chat with listening / processing / streaming / speaking states",
    "Observability: OpenTelemetry tracing, Prometheus metrics, readiness and drain endpoints"
  ],
  visionModels: ["tiny_face_detector", "face_expression"],
  notes: "All tracking runs client-side in the browser; no user data is stored server-side."
};
var get_app_overview_default = defineTool({
  name: "get_app_overview",
  title: "Get app overview",
  description: "Return a structured overview of SimSelf: what it does, its capabilities, and the vision models it uses.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(OVERVIEW, null, 2) }],
    structuredContent: OVERVIEW
  })
});

// src/lib/mcp/tools/check-vision-models.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";
var MODEL_FILES = [
  "tiny_face_detector_model-weights_manifest.json",
  "tiny_face_detector_model.bin",
  "face_expression_model-weights_manifest.json",
  "face_expression_model.bin"
];
var check_vision_models_default = defineTool2({
  name: "check_vision_models",
  title: "Check vision model assets",
  description: "Preflight the public face-api model weight files hosted by the app and report which ones are reachable. Useful for diagnosing emotion-detection failures.",
  inputSchema: {
    baseUrl: z.string().url().describe(
      "Public origin of the deployed app, e.g. https://simulated-self.vercel.app. Model files are checked under <baseUrl>/models/."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ baseUrl }) => {
    let origin;
    try {
      origin = new URL(baseUrl);
    } catch {
      throw new ToolError("baseUrl must be a valid absolute URL.");
    }
    if (origin.protocol !== "https:" && origin.hostname !== "localhost") {
      throw new ToolError("baseUrl must use https (or be localhost).");
    }
    const results = await Promise.all(
      MODEL_FILES.map(async (file) => {
        const url = new URL(`/models/${file}`, origin).toString();
        const started = Date.now();
        try {
          const res = await fetch(url, { method: "GET", redirect: "follow" });
          const bytes = res.ok ? (await res.arrayBuffer()).byteLength : 0;
          return {
            file,
            url,
            ok: res.ok,
            status: res.status,
            bytes,
            latencyMs: Date.now() - started
          };
        } catch (error) {
          return {
            file,
            url,
            ok: false,
            status: 0,
            bytes: 0,
            latencyMs: Date.now() - started,
            error: error instanceof Error ? error.message : String(error)
          };
        }
      })
    );
    const summary = { ok: results.every((r) => r.ok), checked: results.length, results };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary,
      isError: !summary.ok
    };
  }
});

// src/lib/mcp/tools/explain-tracking-pipeline.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var PIPELINES = {
  pose: {
    title: "Body & hand pose",
    stages: [
      "Webcam frame captured from <video> at ~30Hz",
      "MediaPipe Pose + Hands produce 33 body and 21-per-hand landmarks",
      "Hands are re-ordered into a fixed [leftHand, rightHand] tuple with selfie-mirror label correction",
      "Landmarks written to mutable refs at full rate; React state throttled to ~10Hz",
      "HumanoidRobot converts landmarks to world space (x*4, y*3, z*2) and locks the palm to the pose wrist joint"
    ],
    troubleshooting: "If palms look detached, the finger and body z-scales have diverged; both must use z*2."
  },
  emotion: {
    title: "Facial emotion",
    stages: [
      "Frame transferred to a Web Worker as a zero-copy ImageBitmap",
      "face-api.js TinyFaceDetector (inputSize multiple of 32) + expression net run in the worker",
      "Scores smoothed over a sliding window, with a high-confidence bypass for clear expressions",
      "Brightness-based heuristic fallback if the worker or model weights fail to load"
    ],
    troubleshooting: "Check model weights with check_vision_models; tune thresholds in the in-app Emotion Settings panel."
  },
  calibration: {
    title: "Hand calibration",
    stages: [
      "Collect palm landmark samples across a short capture window",
      "Build an orthonormal basis via SVD from wrist/index/pinky landmarks",
      "Correct handedness for the mirrored selfie view",
      "Apply a One-Euro filter to the resulting quaternion to suppress jitter"
    ],
    troubleshooting: "Drift usually means recalibration is needed under the current lighting."
  },
  voice: {
    title: "Voice chat",
    stages: [
      "Web Speech API captures and transcribes speech",
      "Transcript streamed to the LLM; tokens surfaced live as partialResponse",
      "AbortController enforces a 15s timeout with exponential-backoff retries",
      "Full reply spoken via speechSynthesis once the stream terminates"
    ],
    troubleshooting: "Missing API configuration surfaces as a NOT_CONFIGURED error in the HUD."
  }
};
var explain_tracking_pipeline_default = defineTool3({
  name: "explain_tracking_pipeline",
  title: "Explain a tracking pipeline",
  description: "Explain how one of SimSelf's pipelines works (pose, emotion, calibration, voice), including stages and troubleshooting hints.",
  inputSchema: {
    pipeline: z2.enum(["pose", "emotion", "calibration", "voice"]).describe("Which pipeline to explain.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ pipeline }) => {
    const detail = PIPELINES[pipeline];
    return {
      content: [{ type: "text", text: JSON.stringify(detail, null, 2) }],
      structuredContent: detail
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "simself",
  title: "SimSelf",
  version: "0.1.0",
  instructions: "Tools for SimSelf, a browser-based pose/emotion tracking and 3D avatar app. Use `get_app_overview` for what the app does, `explain_tracking_pipeline` for how the pose, emotion, calibration or voice pipelines work, and `check_vision_models` to preflight the public face-api model weight files on a deployed instance.",
  tools: [get_app_overview_default, explain_tracking_pipeline_default, check_vision_models_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
